name: Atualizar estrutura do projeto (TREE.md)

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  generate-tree:
    # Executar apenas quando o PR for merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Instalar UV
        run: |
          curl -Ls https://astral.sh/uv/install.sh | sh

      - name: Executar script Python para gerar TREE.md
        run: |
          uv pip install rich
          python -m venv .venv
          . .venv/bin/activate
          uv pip install rich
          python src/scripts/util_generate_tree.py --output docs/TREE.md
          deactivate

      - name: Commit e push do arquivo TREE.md
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs/TREE.md
          git commit -m "docs: atualiza estrutura de diretórios em docs/TREE.md"
          git push
